### ISSUE TITLE
star_bulk.sh

### ISSUE THREAD

**Issue by abhercam** [cellgeni/bulk_rnaseq#1]
Dear cellgeni IT,

I would like to let you know a couple of things that I had to modify in order to being able to run the star_bulk.sh

1) I had to add to being able to run it: module load singularity

(I also added module load star, I don't know if this one was necessary, but just in case)

2) line 131: $CMD samtools view -@$CPUS -F8 -d NH:1 -O BAM Aligned.sortedByCoord.out.bam | samtools sort -@$CPUS -n -O BAM - > Uniq_paired_namesorted.bam
I had to modify as follow (adding $CMD):
$CMD samtools view -@$CPUS -F8 -d NH:1 -O BAM Aligned.sortedByCoord.out.bam | $CMD samtools sort -@$CPUS -n -O BAM - > Uniq_paired_namesorted.bam

I think those are all the things I needed to modify to make it run.

Thank you, have a nice week!!

**Comment by apredeus** [comment]
Hi @abhercam - 

You don't necessarily need to load the module; you can also add the directory like `/software/singularity/v3.10.0/bin/` to your `$PATH` variable (and restart your bash shell). This should make `singularity` available. 

As to `module load star`, this kind of defeats the purpose of using singularity - since you only want to have one exactly specific version of the tools to use! So, while it probably didn't change anything, you still should not do it. 

Nice catch with `samtools` -> `$CMD samtools`, I'll fix that in the future release.
